version: '3.8'

services:
  api-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-service:latest
    container_name: api-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/ecommerce
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5Dialect
      - SECURITY_JWT_SECRET=your_secret_key
      - SECURITY_JWT_EXPIRATION=3600000
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka:8761/eureka/
    depends_on:
      - mysql
      - eureka

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: api_db
    ports:
      - "3306:3306"

  eureka:
    image: eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"

